name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  run_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Build and javascript docker image
      uses: actions/Playwright@v1

