name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  run_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Run Playwright tests
      run: |
        docker login --username Sruthin86 --password ${{ secrets.GH.PAT }}
        docker run ghcr.io/sruthin86/playwright:latest npx playwright test --browser=firefox

