name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Build and push javascript docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ./javascript/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: 'latest'
    - name: Run Playwright tests
      run: docker run playwright-jammy npx playwright test --browser=firefox

