name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the docker image
      run: docker build ./javascript -t playwright-jammy
    - name: Cache docker image
      uses: docker/setup-buildx-action@v2
      with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    - name: Run Playwright tests
      run: docker run playwright-jammy npx playwright test --browser=firefox

