name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  run_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Pull the image from container registry
      run: docker login --username Sruthin86 --password ${{ secrets.GH_PAT }} ghcr.io
    - name: Run tests
      run: docker run ghcr.io/sruthin86/playwright:latest npx playwright test --browser=firefox

